import type { MoveSet } from "./frameData";

/**
 * Conjunto de golpes base — a "cadeia mágica" do gênero.
 *
 * Tudo aqui é NÚMERO. Balancear o jogo é editar este arquivo; nenhuma linha de
 * lógica muda. Um golpe rápido demais, um combo fácil demais, um especial caro
 * demais — tudo se resolve mexendo em `startup`, `hitstun` e `cancels`.
 *
 * A cadeia clássica é `L → M → H → lançador → combo aéreo`. Cada golpe cancela
 * no seguinte, e o lançador joga o oponente para cima abrindo a sequência
 * aérea. É a estrutura que Marvel vs Capcom popularizou.
 */
export const MOVESET_BASE: MoveSet = {
  soco_L: {
    id: "soco_L",
    name: "Soco leve",
    input: { kind: "botao", button: "L" },
    height: "alto",
    startup: 4,
    active: 3,
    recovery: 8,
    hitboxes: [{ x: 20, y: -40, w: 26, h: 18 }],
    hit: { damage: 40, hitstun: 16, blockstun: 12, pushback: 2, guard: "qualquer" },
    cancels: { into: ["soco_M", "chute_H", "especial_236L"], from: 1 },
    animation: "attack",
  },
  soco_M: {
    id: "soco_M",
    name: "Soco médio",
    input: { kind: "botao", button: "M" },
    height: "alto",
    startup: 7,
    active: 4,
    recovery: 12,
    hitboxes: [{ x: 22, y: -44, w: 32, h: 22 }],
    hit: { damage: 70, hitstun: 20, blockstun: 14, pushback: 3, guard: "qualquer" },
    cancels: { into: ["chute_H", "lancador", "especial_236L"], from: 1 },
    animation: "strike",
  },
  chute_baixo: {
    id: "chute_baixo",
    name: "Chute baixo",
    input: { kind: "botao", button: "L", crouch: true },
    height: "baixo",
    startup: 5,
    active: 3,
    recovery: 10,
    hitboxes: [{ x: 20, y: -12, w: 30, h: 14 }],
    hit: { damage: 45, hitstun: 16, blockstun: 12, pushback: 2, guard: "baixo" },
    cancels: { into: ["soco_M", "lancador"], from: 1 },
    animation: "crouch",
  },
  chute_H: {
    id: "chute_H",
    name: "Chute forte",
    input: { kind: "botao", button: "H" },
    height: "medio",
    startup: 10,
    active: 5,
    recovery: 18,
    hitboxes: [{ x: 26, y: -36, w: 40, h: 24 }],
    hit: { damage: 100, hitstun: 26, blockstun: 16, pushback: 6, guard: "qualquer" },
    cancels: { into: ["lancador", "especial_236L", "hyper_236236"], from: 1 },
    animation: "attack",
  },
  chute_giratorio: {
    id: "chute_giratorio",
    name: "Chute giratório",
    input: { kind: "motion", motion: "214", button: "H" },
    height: "medio",
    startup: 12,
    active: 8,
    recovery: 20,
    hitboxes: [{ x: 24, y: -38, w: 46, h: 30 }],
    hit: { damage: 120, hitstun: 28, blockstun: 14, pushback: 9, guard: "qualquer" },
    cancels: { into: ["hyper_236236"], from: 3 },
    animation: "special",
  },
  lancador: {
    id: "lancador",
    name: "Lançador",
    input: { kind: "botao", button: "H", crouch: true },
    height: "medio",
    startup: 9,
    active: 4,
    recovery: 24,
    hitboxes: [{ x: 18, y: -50, w: 30, h: 50 }],
    hit: {
      damage: 80,
      hitstun: 40,
      blockstun: 12,
      pushback: 0,
      guard: "qualquer",
      launcher: true,
      juggle: true,
    },
    cancels: { into: ["aereo_L", "aereo_H"], from: 1 },
    animation: "strike",
  },
  aereo_L: {
    id: "aereo_L",
    name: "Aéreo leve",
    input: { kind: "botao", button: "L", air: true },
    height: "aereo",
    startup: 5,
    active: 4,
    recovery: 10,
    hitboxes: [{ x: 18, y: -30, w: 28, h: 20 }],
    hit: { damage: 50, hitstun: 22, blockstun: 12, pushback: 1, guard: "alto", juggle: true },
    cancels: { into: ["aereo_H"], from: 1 },
    animation: "jump",
  },
  aereo_H: {
    id: "aereo_H",
    name: "Aéreo forte",
    input: { kind: "botao", button: "H", air: true },
    height: "aereo",
    startup: 8,
    active: 5,
    recovery: 16,
    hitboxes: [{ x: 22, y: -34, w: 36, h: 26 }],
    hit: { damage: 90, hitstun: 30, blockstun: 14, pushback: 7, guard: "alto", juggle: true },
    animation: "jump",
  },
  especial_236L: {
    id: "especial_236L",
    name: "Especial — projétil",
    input: { kind: "motion", motion: "236", button: "L" },
    height: "medio",
    startup: 13,
    active: 6,
    recovery: 22,
    hitboxes: [{ x: 40, y: -34, w: 40, h: 22 }],
    hit: { damage: 110, hitstun: 24, blockstun: 15, pushback: 8, guard: "qualquer" },
    cancels: { into: ["hyper_236236"], from: 1 },
    animation: "special",
  },
  contra_623: {
    id: "contra_623",
    name: "Reversal",
    input: { kind: "motion", motion: "623", button: "H" },
    height: "medio",
    startup: 6,
    active: 8,
    recovery: 30,
    hitboxes: [{ x: 16, y: -60, w: 32, h: 60 }],
    hit: { damage: 130, hitstun: 34, blockstun: 10, pushback: 10, guard: "qualquer", launcher: true },
    invulnerable: 6,
    animation: "special",
  },
  agarrar: {
    id: "agarrar",
    name: "Agarrar",
    input: { kind: "botao", button: "L" },
    height: "medio",
    startup: 6,
    active: 3,
    recovery: 20,
    hitboxes: [{ x: 14, y: -50, w: 24, h: 46 }],
    hit: { damage: 90, hitstun: 40, blockstun: 0, pushback: 12, guard: "qualquer" },
    grab: true,
    cancels: { into: ["arremesso"], from: 1 },
    animation: "strike",
  },
  arremesso: {
    id: "arremesso",
    name: "Arremesso",
    input: { kind: "botao", button: "H" },
    height: "medio",
    startup: 4,
    active: 4,
    recovery: 22,
    hitboxes: [{ x: 16, y: -46, w: 30, h: 44 }],
    hit: { damage: 140, hitstun: 50, blockstun: 0, pushback: 26, guard: "qualquer", juggle: true },
    animation: "strike",
  },
  rolamento: {
    id: "rolamento",
    name: "Rolamento",
    input: { kind: "botao", button: "L", crouch: true },
    height: "baixo",
    startup: 3,
    active: 12,
    recovery: 8,
    hitboxes: [{ x: 10, y: -18, w: 26, h: 18 }],
    hit: { damage: 20, hitstun: 12, blockstun: 8, pushback: 4, guard: "qualquer" },
    dodgeFrames: 12,
    animation: "dash",
  },
  investida: {
    id: "investida",
    name: "Investida",
    input: { kind: "motion", motion: "41236", button: "M" },
    height: "medio",
    startup: 8,
    active: 10,
    recovery: 16,
    hitboxes: [{ x: 22, y: -44, w: 44, h: 40 }],
    hit: { damage: 95, hitstun: 26, blockstun: 14, pushback: 10, guard: "qualquer" },
    dodgeFrames: 6,
    cancels: { into: ["lancador", "hyper_236236"], from: 2 },
    animation: "dash",
  },
  especial_vida: {
    id: "especial_vida",
    name: "Especial de vida",
    input: { kind: "motion", motion: "623", button: "M" },
    height: "medio",
    startup: 7,
    active: 12,
    recovery: 26,
    hitboxes: [{ x: 20, y: -58, w: 60, h: 58 }],
    hit: { damage: 200, hitstun: 36, blockstun: 18, pushback: 12, guard: "qualquer", launcher: true },
    healthCost: 70,
    invulnerable: 5,
    cancels: { into: ["aereo_L"], from: 2 },
    animation: "special",
  },
  hyper_236236: {
    id: "hyper_236236",
    name: "Hyper",
    input: { kind: "hyper", motion: "236236", cost: 1 },
    height: "medio",
    startup: 8,
    active: 20,
    recovery: 34,
    hitboxes: [{ x: 24, y: -56, w: 90, h: 56 }],
    hit: { damage: 320, hitstun: 44, blockstun: 24, pushback: 14, guard: "qualquer" },
    meterCost: 1,
    invulnerable: 8,
    animation: "special",
  },
};

/** A cadeia que todo personagem deve conseguir executar. */
/** Cadeia de agarrão: pega quem está bloqueando e arremessa. */
export const COMBO_AGARRAO = ["agarrar", "arremesso"];

export const COMBO_BASICO = ["soco_L", "soco_M", "chute_H", "lancador", "aereo_L", "aereo_H"];
